In [1]:
import sklearn

In [2]:
sklearn.__version__

'0.24.2'

In [3]:
from sklearn.datasets import load_iris

#  DecisionTreeRegressor 회귀
# DecisionTreeClassifier 분류

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
import pandas as pd  # 전처리할때 많이 사용

In [5]:
iris = load_iris(as_frame=True)

In [6]:
iris

{'data':      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 'target': 0     

In [7]:
type(iris)

sklearn.utils.Bunch

In [8]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [9]:
iris['data']

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
iris.data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
iris_df = iris['data']

In [13]:
iris_df['target'] = iris['target']

In [14]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [15]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [17]:
x_train, x_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=0)

In [18]:
type(x_train)

pandas.core.frame.DataFrame

In [19]:
dt_clf = DecisionTreeClassifier(random_state=11)     # 쉬프트탭  쫘르르나오는거 하이퍼파라메타?라고함

In [20]:
dt_clf.fit(x_train,y_train)

DecisionTreeClassifier(random_state=11)

In [21]:
pred = dt_clf.predict(x_test)

In [59]:
pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [58]:
y_test

114    2
62     1
33     0
107    2
7      0
100    2
40     0
86     1
76     1
71     1
134    2
51     1
73     1
54     1
63     1
37     0
78     1
90     1
45     0
16     0
121    2
66     1
24     0
8      0
126    2
22     0
44     0
97     1
93     1
26     0
Name: target, dtype: int32

In [57]:
from sklearn.metrics import accuracy_score         # metrics : 평가와 관련된 모든것들이 들어가 있음

In [56]:
accuracy_score(y_test,pred)

1.0

In [76]:
def test1(a,b):
    '''
    이함수는 결과값이 3개로 나갑니다.
    '''
    return a+b, a-b, a*b

In [ ]:
test1()

In [75]:
result = test1(1,2)

In [71]:
result

(3, -1, 2)

In [72]:
r1, r2, r3 = test1(3,4)

In [73]:
r1

7

# 과적합 참조
![과적합](과적합.png)

```
print('hello')
```

In [92]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [119]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [120]:
kfold = KFold(n_splits=5,shuffle=True)

In [121]:
cv_accuracy=[]

In [122]:
iris.data.shape

(150, 4)

In [123]:
n_iter = 0
for train_index,test_index in kfold.split(iris.data):
    # print(train_index)
    # print('-'*50)
    # print(test_index)
    # print()
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    # print(x_train,x_test)
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    n_iter+=1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수:{x_train.shape[0]}, 검증데이터 건수:{x_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9333333333333333
2번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9333333333333333
3번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9333333333333333
4번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9666666666666667
5번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9666666666666667
0.9466666666666667


In [126]:
kfold = KFold(n_splits=5,shuffle=True)
n_iter = 0
for train_index,test_index in kfold.split(iris.data):
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    # print(type(pd.Series(y_train))) 
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

 


학습용데이터 분포:
 1    43
2    39
0    38
dtype: int64
검증용데이터 분포:
 0    12
2    11
1     7
dtype: int64
학습용데이터 분포:
 0    44
2    40
1    36
dtype: int64
검증용데이터 분포:
 1    14
2    10
0     6
dtype: int64
학습용데이터 분포:
 1    43
0    40
2    37
dtype: int64
검증용데이터 분포:
 2    13
0    10
1     7
dtype: int64
학습용데이터 분포:
 2    43
1    39
0    38
dtype: int64
검증용데이터 분포:
 0    12
1    11
2     7
dtype: int64
학습용데이터 분포:
 2    41
0    40
1    39
dtype: int64
검증용데이터 분포:
 1    11
0    10
2     9
dtype: int64


In [130]:
from sklearn.model_selection import StratifiedKFold   # 컨트롤 쉬프트 마이너스 

In [132]:
skfold = KFold(n_splits=5,shuffle=True)
n_iter = 0
for train_index,test_index in skfold.split(iris.data,iris.target):
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    # print(type(pd.Series(y_train))) 
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

 

학습용데이터 분포:
 1    41
2    41
0    38
dtype: int64
검증용데이터 분포:
 0    12
1     9
2     9
dtype: int64
학습용데이터 분포:
 1    41
2    40
0    39
dtype: int64
검증용데이터 분포:
 0    11
2    10
1     9
dtype: int64
학습용데이터 분포:
 1    41
0    40
2    39
dtype: int64
검증용데이터 분포:
 2    11
0    10
1     9
dtype: int64
학습용데이터 분포:
 0    42
1    40
2    38
dtype: int64
검증용데이터 분포:
 2    12
1    10
0     8
dtype: int64
학습용데이터 분포:
 2    42
0    41
1    37
dtype: int64
검증용데이터 분포:
 1    13
0     9
2     8
dtype: int64


In [136]:
skfold = KFold(n_splits=5,shuffle=True)
n_iter = 0
cv_accuravy=[]
for train_index,test_index in skfold.split(iris.data,iris.target):
    # print(train_index)
    # print('-'*50)
    # print(test_index)
    # print()
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    # print(x_train,x_test)
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    n_iter+=1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수:{x_train.shape[0]}, 검증데이터 건수:{x_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9666666666666667
2번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9333333333333333
3번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9333333333333333
4번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9666666666666667
5번째 교차검증
학습데이터 건수:120, 검증데이터 건수:30
정확도:0.9666666666666667
0.9422222222222223


In [4]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

In [5]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [6]:
scores = cross_val_score(dt_clf,
                iris_data.data,
                iris_data.target,
                scoring='accuracy',
                cv=3)

In [7]:
import numpy as np
print('교차 검증별 정확도', scores)
print('평균 교차 검증 정확도',np.mean(scores))

교차 검증별 정확도 [0.98 0.94 0.98]
평균 교차 검증 정확도 0.9666666666666667


In [8]:
# gridsearchcv -> 교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에 

In [9]:
from sklearn.model_selection import GridSearchCV,train_test_split


In [10]:
grid_param = {'max_depth':[1,2,3],
              'min_samples_split':[2,3]}

In [11]:
iris = load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=121)
dtree = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dtree,
                          param_grid=grid_param,
                          cv=3,
                          refit=True)
grid_dtree.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [12]:
grid_dtree.cv_results_  # 괄호 열고닫기가 필요없음

{'mean_fit_time': array([0.00066471, 0.00066495, 0.00033228, 0.00066471, 0.00099691,
        0.00099683]),
 'std_fit_time': array([4.70022017e-04, 4.70190252e-04, 4.69909263e-04, 4.70024920e-04,
        1.36730278e-06, 8.48537942e-07]),
 'mean_score_time': array([0.00033228, 0.        , 0.00066495, 0.00099651, 0.00033299,
        0.        ]),
 'std_score_time': array([0.00046991, 0.        , 0.00047019, 0.00081332, 0.00047092,
        0.        ]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'ma

In [13]:
import pandas as pd

In [14]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)

In [15]:
scores_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [16]:
scores_df[['params',
           'rank_test_score',
          'split0_test_score',
           'split1_test_score',
           'split2_test_score' ]]

params  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}                5   
1  {'max_depth': 1, 'min_samples_split': 3}                5   
2  {'max_depth': 2, 'min_samples_split': 2}                3   
3  {'max_depth': 2, 'min_samples_split': 3}                3   
4  {'max_depth': 3, 'min_samples_split': 2}                1   
5  {'max_depth': 3, 'min_samples_split': 3}                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [17]:
grid_dtree.best_score_

0.975

In [18]:
# 예측  predict

pred = grid_dtree.best_estimator_.predict(x_test)

In [19]:
# 정확도

from sklearn.metrics import accuracy_score

In [20]:
print('best estimator 정확도', accuracy_score(y_test,pred))

best estimator 정확도 0.9666666666666667


In [21]:
# -- 교차검증까지 --    -> 데이터 준비가 다되었어요 

In [ ]:
# 데이터 인코딩

# 머신러닝을 위한 대표적인 인코딩 방식은 레이블 인코딩


In [22]:
from sklearn.preprocessing import LabelEncoder

In [49]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [50]:
encoder = LabelEncoder()
encoder.fit(items)   # fit --> 목록 작성
labels = encoder.transform(items)

In [51]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [52]:
encoder.classes_                # instance -> 저장

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [53]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [54]:
# 글자로 하는이유 글자를 못받아들여서 숫자로 해야함

In [93]:
# 원핫 인코딩  피처값의 우형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 
            # 나머지 칼럼에는 0을 표시하는 방식


In [94]:
from sklearn.preprocessing import OneHotEncoder

In [95]:
items = [['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서'], dtype='<U5' ]]

SyntaxError: invalid syntax (Temp/ipykernel_34636/2498683266.py, line 1)

In [96]:
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [97]:
labels.shape


(8,)

In [98]:
labels = labels.reshape(-1,1)
labels.shape

(8, 1)

In [99]:
oh_encoder = OneHotEncoder(sparse=True)
oh_labels = oh_encoder.fit_transform(labels)      # 림ndim 차원수

In [100]:
oh_encoder.categories_

[array([0, 1, 2, 3, 4, 5], dtype=int64)]

In [101]:
oh_encoder.sparse

True

In [102]:
oh_encoder

OneHotEncoder()

In [103]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [104]:
df = pd.DataFrame({'item': ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [105]:
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [106]:
import pandas as pd

In [109]:
pd.get_dummies(df).values


array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)

In [110]:
# 표준화 정규화