In [1]:
from sklearn.base import BaseEstimator

In [47]:
class MyDummyClassfier(BaseEstimator):
    def fit(self, X, y=None):
        pass
    
    def predict(self,X):
        import numpy as np
        pred = np.zeros((X.shape[0],1))
        for i in range(X.shape[0]):
            if X['Sex'].iloc[i]==1:
                pred[i]=0
            else:
                pred[i] = 1
            
        return pred

In [48]:
dummy = MyDummyClassfier()

In [49]:
dummy.fit(1)

In [50]:
# loc -> 원래 부여된 값  iloc -> 

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [56]:
def fillna(df):
    df['Age'].fillna(df['Age'].mean(),inplace = True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0, inplace = True)
    return df

def drop_features(df):
    df.drop(columns = ['PassengerId', 'Name', 'Ticket'], inplace=True) 
    return df

def format_features(df):
    from sklearn.preprocessing import LabelEncoder     # 필요한 import를 함수에 넣어주는 것도 좋다.
    df['Cabin'] = df['Cabin'].str[0]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelEncoder()
        df[feature] = le.fit_transform(df[feature])
    return df

def transform_features(df):         # 만들어진 함수를 차례대로 실행하는 함수.
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    return df

In [57]:
titanic_df = pd.read_csv('./titanic_train.csv')
y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop(columns=['Survived'])
X_titanic_df = transform_features(X_titanic_df)
X_train,X_test,y_train,y_test = train_test_split(X_titanic_df,
                                                 y_titanic_df,
                                                 test_size = 0.2,
                                                 random_state = 11)

In [58]:
myclf = MyDummyClassfier()
myclf.fit(X_train, y_train)
pred = myclf.predict(X_test)
accuracy_score(y_test,pred)

0.8324022346368715

In [59]:
from sklearn.datasets import load_digits

In [66]:
digits = load_digits()

In [67]:
digits.data[2].reshape(8,8)

array([[ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.],
       [ 0.,  0.,  3., 16., 15., 14.,  0.,  0.],
       [ 0.,  0.,  8., 13.,  8., 16.,  0.,  0.],
       [ 0.,  0.,  1.,  6., 15., 11.,  0.,  0.],
       [ 0.,  1.,  8., 13., 15.,  1.,  0.,  0.],
       [ 0.,  9., 16., 16.,  5.,  0.,  0.,  0.],
       [ 0.,  3., 13., 16., 16., 11.,  5.,  0.],
       [ 0.,  0.,  0.,  3., 11., 16.,  9.,  0.]])

In [68]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [69]:
digits.target[2]

2

In [71]:
digits.data.min()

0.0

In [83]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pl

class MyFakeClassifier(BaseEstimator):
    def fit (self,X,y):
        pass
        

In [89]:
    #입력값으로 들어오는 x 데이터 세트의 크기만큼 모두 0 값으로 만들어서 반환
def predict(self, X,):
    return np.zeros((len(X),1),(dtype=bool)

IndentationError: expected an indented block (Temp/ipykernel_13404/2204521500.py, line 3)

In [87]:
# 사이킷런의 내장 데이터 세트인 load_digits(를) 이용해 minist 데이토 로딩
digits = load_digits()

In [ ]:
digits 번호가 7이면 true이고 이름 astype(int)

In [ ]:
array([[405,]])